(defun mul (a b)
  (defun even? (n)
    (= (mod n 2) 0))
  (defun double (n)
    (* 2 n))
  (defun halve (n)
    (/ n 2))
  (defun mul-iter (a b acc)
    (cond ((= b 0) 0)
          ((= b 1) (+ a acc))
          ((even? b)
           (mul-iter (double a) (halve b) acc))
          (t (mul-iter a (- b 1) (+ acc a)))))
  (mul-iter a b 0))

(mul 3 100)
