(define (square-sum-larger a b c)
    (define (sqr a)
        (* a a))
    (define (square-sum a b)
        (+ (sqr a) (sqr b)))
    (cond ((and (>= a b) (>= b c)) (square-sum a b))
          ((and (>= a b) (>= c b)) (square-sum a c))
          ((and (>= b a) (>= a c)) (square-sum b a))
          ((and (>= b a) (>= c a)) (square-sum b c))))
